pacman::p_load(
  here,
  gtsummary,
  tidyverse,
  broom,
  broom.helpers,
  scales,
  flextable
)

# Data ---------------------------------------------------------------
sdg_data <- readRDS(here("output", "UHRI_UPR_enhanced.rds")) |> 
  mutate(response_upr = fct_recode(response_upr, 
                                   "Noted" = "Partially supported"),
         response_upr = fct_relevel(response_upr, "Noted")) |> 
  mutate(
    # make sure the maternal health variable doesn't include recommendations related to abortion (these figure only in the "abortion" variable)
    Maternal_health = case_when(abortion != "Other" ~ "Other", .default = maternal_health),
  ) |> 
  relocate(Maternal_health, abortion, .after = maternal_health) |> 
  droplevels()

state_geo <- readRDS(here("output", "state_geo_enhanced.rds"))
source(here("code", "theme_labels.R"))

# Loop through to load pre-processed datasets
# These files were generated by running the code/external_data_OData.R file
for (file_name in list.files(path = here("data", "API_data"), pattern = "\\.rds$")) {
  object_name <- gsub("\\.rds$", "", file_name)
  assign(object_name, readRDS(here("data", "API_data", file_name)))
}

# Prepare data to add into table ----

## Indicator data ----
MMR_table <- MMR |> 
  filter(!is.na(country_name)) |> 
  filter(country_name!="Cook Islands", country_name != "Greenland") |> 
  select(ParentLocation, COUNTRY, country_name, YEAR, NumericValue) |> 
  mutate(NumericValue = round(NumericValue)) |> 
  rename(MMR = NumericValue) |> 
  mutate(
    mmr_cat4 = factor(case_when(
      MMR < 20 ~ "<20",
      MMR < 100 ~ "20-99",
      MMR < 300 ~ "100-299",
      MMR >= 300 ~ "300+",
      .default = NA), 
      
      levels = c("<20", "20-99","100-299", "300+")
    ),
    mmr_cat3 = factor(case_when(
      MMR < 20 ~ "<20",
      MMR < 100 ~ "20-99",
      MMR >= 100 ~ "100+",
      .default = NA), 
      levels = c("<20", "20-99","100+")
    ),
    mmr_cat2 = factor(case_when(
      MMR < 100 ~ "<100",
      MMR >= 100 ~ "100+",
      .default = NA), 
      levels = c("<100","100+")
    )
  ) |> 
  filter(YEAR %in% c(2023)) |> 
  pivot_wider(values_from = c(MMR, mmr_cat4, mmr_cat3), names_from = YEAR)

institutional_birth_table <- institutional_birth |> 
  group_by(country_name) |> 
  slice_max(YEAR) |> 
  ungroup() |> 
  select(COUNTRY, NumericValue) |> 
  rename(institutional_birth = NumericValue) |> 
  mutate(
    institutional_birth_cat = factor(case_when(
      institutional_birth >= 98 ~ "98+",
      institutional_birth >= 90 ~ "90-97",
      institutional_birth >= 65 ~ "65-89",
      institutional_birth < 65 ~ "<65"
    )))

skilled_birth_table <- skilled_birth |> 
  group_by(country_name) |> 
  slice_max(YEAR) |> 
  ungroup() |> 
  select(COUNTRY, NumericValue) |> 
  rename(skilled_birth = NumericValue) |> 
  mutate(
    skilled_birth_cat = factor(case_when(
      skilled_birth >= 98 ~ "98+",
      skilled_birth >= 90 ~ "90-97",
      skilled_birth >= 65 ~ "65-89",
      skilled_birth < 65 ~ "<65"
    )))

## Skilled birth change calculation ----
skilled_birth_max <- skilled_birth |> 
  filter(!is.na(COUNTRY)) |> 
  filter(YEAR >=2005) |>
  group_by(country_name) |> 
  slice_max(YEAR) |> 
  ungroup() |> 
  select(YEAR, COUNTRY, NumericValue) |> 
  rename(skilled_birth_max = NumericValue, YEAR_max = YEAR)

skilled_birth_min <- skilled_birth |> 
  filter(!is.na(COUNTRY)) |> 
  filter(YEAR >= 2005) |> 
  group_by(country_name) |> 
  slice_min(YEAR) |> 
  ungroup() |> 
  select(YEAR, COUNTRY, NumericValue) |> 
  rename(skilled_birth_min = NumericValue, YEAR_min = YEAR)

skilled_birth_change = skilled_birth_min |> left_join(skilled_birth_max) |> 
  filter(!is.na(skilled_birth_max)) |> 
  filter(YEAR_min != YEAR_max) |> 
  mutate(
    num_years = YEAR_max -YEAR_min,
    skilled_birth_change = skilled_birth_max - skilled_birth_min,
    skilled_birth_log_change = log(skilled_birth_max) - log(skilled_birth_min)
  ) |> 
  rename(skilled_birth_year_min = YEAR_min, skilled_birth_year_max = YEAR_max) |> 
  # filter(num_years >= 5) |>
  select(COUNTRY, skilled_birth_max, skilled_birth_min, skilled_birth_change, skilled_birth_log_change, 
         skilled_birth_year_min, skilled_birth_year_max, num_years)

# skilled_birth_change |> ggplot(aes(x = num_years, y = skilled_birth_change))+
#   geom_point()+
#   geom_smooth(method = "lm")

family_planning_table <- family_planning |> 
  group_by(country_name) |> 
  slice_max(YEAR) |> 
  ungroup() |> 
  select(COUNTRY, NumericValue) |> 
  rename(family_planning = NumericValue) |> 
  mutate(
    family_planning_cat = factor(case_when(
      family_planning >= 80 ~ "80+",
      family_planning >= 60  ~ "60-79",
      family_planning >= 40 ~ "50-59",
      family_planning < 40 ~ "<40"
    )))

unintended_pregnancy_table <- unintended_pregnancy |> 
  filter(Dim1 == "UNCERTAINTY_INTERVAL_UI95") |> 
  select(COUNTRY, NumericValue) |> 
  rename(unintended_pregnancy = NumericValue)

UHC_SCI_RMNCH_table <- UHC_SCI_RMNCH |> 
  # group_by(SpatialDim) |> 
  # slice_max(TimeDim) |> 
  # ungroup() |> 
  filter(TimeDim %in% c(2005, 2023)) |> 
  select(SpatialDim, TimeDim, NumericValue) |> 
  rename(UHC_RMNCH = NumericValue, year = TimeDim) |> 
  mutate(UHC_RMNCH_cat = factor(case_when(
    UHC_RMNCH >= 70 ~ "70+",
    UHC_RMNCH >= 50  ~ "50-69",
    UHC_RMNCH < 50 ~ "<50",
  ))
  ) |> 
  pivot_wider(names_from = year, values_from = c(UHC_RMNCH, UHC_RMNCH_cat))

anc4_table <- anc4 |> 
  filter(Dim1 == "AGEGROUP_YEARS20-49") |> 
  filter(!is.na(NumericValue)) |> 
  group_by(country_name) |> 
  slice_max(YEAR) |> 
  ungroup() |> 
  filter(YEAR >= 2010) |> 
  select(COUNTRY, NumericValue) |> 
  rename(anc4 = NumericValue) |> 
  mutate(
    anc4_cat = factor(case_when(
      anc4 >= 90 ~ "90+",
      anc4 >= 70  ~ "70-89",
      anc4 >= 50 ~ "50-69",
      anc4 < 50 ~ "<50"
    )))

contraceptive_prevalence_ANY_table <- contraceptive_prevalence_ANY |> 
  filter(!is.na(CPR_any)) |> 
  filter(YEAR > 2010) |> 
  group_by(country_code) |> slice_max(YEAR) |> ungroup() |> 
  select(CPR_any, country_code) |> 
  mutate(
    CPR_any_cat = factor(case_when(
      CPR_any >= 70 ~ "70+",
      CPR_any >= 50  ~ "50-69",
      CPR_any >= 20 ~ "20-49",
      CPR_any < 20 ~ "<20"
    )))

GDP_table <- GDP |> mutate(GDP_05_19 = (GDP_2019 - GDP_2005)/GDP_2005)

literacy_table <- literacy_long |> 
  filter(!is.na(literacy_long)) |> 
  filter(year >= 1990 & year <= 2012) |> 
  group_by(country_name) |> 
  filter(year == max(year)) |> ungroup()
# filter(year == min(year)|year==max(year)) |> 
# mutate(literacy_change = literacy_long[year==max(year)] - literacy_long[year==min(year)]) |> 
# mutate(literacy_years_change = max(year)-min(year)) |> 
# ungroup() |> 
# mutate(change_cat = case_when(literacy_change>0 ~ "Improved", literacy_change ==0 ~ "No change", literacy_change <0 ~ "Worsened")) |> 
# arrange(country_name, year)

# literacy_table |> 
#   ggplot(aes(x = year, y = literacy_long, group = country_name)) +
#   geom_line(aes(color = change_cat))


## FCS data ----
FCS_all <- read_csv(here("data", "FCS_status_all.csv")) |> 
  mutate(
    FCS_status2 = fct_recode(FCS_status, "Other FCS" = "Other"),
    FCS_status = "FCS"
  )

## Governance data ----
### WGI dataset ----
# https://data360.worldbank.org/en/dataset/WB_WGI
WGI <- read_csv(here("data", "WB_WGI_WIDEF.csv")) |> 
  janitor::clean_names() |> 
  filter(str_detect(comp_breakdown_1_label,"Metric: Governance estimate")) |> 
  select(ref_area, ref_area_label, indicator_label, c(x1996:x2024)) |> 
  pivot_longer(cols = x1996:x2024, 
               names_to = "year", 
               values_to = "value", 
               values_drop_na = FALSE) |> 
  mutate(
    year = as.numeric(str_remove(year, "x")),
    indicator_label = str_remove(indicator_label, "Worldwide Governance Indicators\\: ")
  ) |> 
  rename(iso3 = ref_area, country = ref_area_label) |> 
  pivot_wider(names_from = indicator_label, values_from = value) |> 
  janitor::clean_names()

WGI_governance <- WGI |> 
  filter(!is.na(government_effectiveness), year>=2005) |> 
  group_by(iso3) |> 
  slice_min(year, n=1) |> ungroup() |> 
  select(iso3, year, government_effectiveness) |> 
  rename(government_effectiveness_baseline = government_effectiveness) |> 
  mutate(government_effectiveness_baseline_cat = factor(
    case_when(
      government_effectiveness_baseline >= 0 ~ "0+",
      government_effectiveness_baseline < -1 ~ "< -1",
      government_effectiveness_baseline < 0 ~ "< 0"
    ), levels = c("0+", "< 0", "< -1")
  ))

WGI_political_stability <- WGI |> 
  filter(!is.na(political_stability), year>=2005) |> 
  group_by(iso3) |> 
  slice_min(year, n=1) |> ungroup() |> 
  select(iso3, year, political_stability) |>
  rename(political_stability_baseline = political_stability) |> 
  mutate(political_stability_baseline_cat = factor(
    case_when(
      political_stability_baseline >= 0 ~ "0+",
      political_stability_baseline < -1 ~ "< -1",
      political_stability_baseline < 0 ~ "< 0"
    ), levels = c("0+", "< 0", "< -1")
  ))

### Government effectiveness ----
# https://data360.worldbank.org/en/indicator/GOV_WGI_GE
governance <- read_csv(here("data", "GOV_WGI_GE_WIDEF.csv")) |> 
  janitor::clean_names() |> 
  filter(comp_breakdown_1_label == "Metric: Governance estimate (approx. -2.5 to +2.5)") |> 
  select(ref_area, ref_area_label, c(x1996:x2024)) |> 
  pivot_longer(cols = x1996:x2024, 
               names_to = "year", 
               values_to = "government_effectiveness", 
               values_drop_na = FALSE) |> 
  mutate(year = as.numeric(str_remove(year, "x"))) |> 
  rename(iso3 = ref_area, country = ref_area_label)
governance_table <- governance |> 
  filter(year >= 2008) |> 
  filter(!is.na(government_effectiveness)) |> 
  group_by(country) |> 
  slice_min(year, n=1) |> 
  rename(government_effectiveness_baseline = government_effectiveness) |> 
  ungroup()

# UNFPA data ----
# https://pdp.unfpa.org/
## Contraceptive prevalence rate, ALL WOMEN ----
# https://pdp.unfpa.org/?data_id=dataSource_8-2%3A82%2CdataSource_8-5%3A7189&org=UNFPAPDP
UNFPA_CPR_any_table <- read_csv(here("data", "UNFPA_CPR_any_ALL.csv")) |> 
  janitor::clean_names() |> 
  rename(loc_id = un_standard_country_or_area_code_m_49) |> 
  left_join(state_geo |> select(iso3, loc_id) |> sf::st_drop_geometry()) |> 
  rename(CPR_any = total) |> 
  # Filtered for their estimates for 2023
  filter(survey_year == 2023) |> 
  filter(source_organization == "FPI") |> 
  # group_by(iso3) |> slice_max(survey_year) |> ungroup() |>
  select(iso3, CPR_any) |> 
  mutate(
    CPR_any_cat = factor(case_when(
      CPR_any >= 70 ~ "70+",
      CPR_any >= 50  ~ "50-69",
      CPR_any >= 20 ~ "20-49",
      CPR_any < 20 ~ "<20"
    )))

UNFPA_CPR_any_long <- read_csv(here("data", "UNFPA_CPR_any_ALL.csv")) |> 
  janitor::clean_names() |> 
  filter(source_organization == "FPI") |> 
  rename(loc_id = un_standard_country_or_area_code_m_49) |> 
  left_join(state_geo |> select(iso3, loc_id) |> sf::st_drop_geometry()) |> 
  rename(CPR_any_long = total, year = survey_year) |> 
  select(CPR_any_long, year, iso3)

## CPR Change Calculation ----
CPR_any <- read_csv(here("data", "UNFPA_CPR_any_ALL.csv")) |> 
  janitor::clean_names() |> 
  rename(loc_id = un_standard_country_or_area_code_m_49) |> 
  left_join(state_geo |> select(iso3, loc_id) |> sf::st_drop_geometry()) |> 
  rename(CPR_any = total) |> 
  filter(survey_year %in% c(2023, 2005)) |>
  # filter(survey_year >= 2005) |> 
  filter(!is.na(CPR_any)) |> 
  filter(!is.na(iso3)) |> 
  filter(source_organization == "FPI") |> 
  select(iso3, CPR_any, survey_year) |> 
  pivot_wider(names_from = survey_year, values_from = CPR_any, id_cols = iso3) |> 
  rename(CPR_any_2023 = `2023`, CPR_any_2005 = `2005`) |> 
  mutate(
    CPR_any_change = CPR_any_2023 - CPR_any_2005,
    CPR_any_log_change = log(CPR_any_2023) - log(CPR_any_2005)
  )

## UPR data ----
n_sup_2_long <- sdg_data |> 
  filter(! cycle %in% c(
    "Cycle 4"
    # , "Cycle 3"
  )) |> 
  # filter(state_under_review %in% c(mmr_most$country_name)) |> 
  mutate(state_under_review = factor(state_under_review)) |> 
  # filter(response_upr %in% c("Supported", "Noted")) |> 
  group_by(state_under_review, response_upr) |> 
  summarise(across(c(health_related:other_health_related), ~ sum(.x != "Other"))) |> 
  ungroup() |>
  filter(response_upr %in% c("Supported", "Noted")) |>
  pivot_longer(
    cols = health_related:other_health_related,
    names_to = "theme",
    values_to = "n"
  ) |> 
  arrange(state_under_review, theme, response_upr) |> 
  group_by(state_under_review, theme) |> 
  mutate(
    n_tot = sum(n),
    perc = round(n/n_tot*100,1)
  ) |> 
  ungroup() |> 
  filter(response_upr == "Supported") |> 
  group_by(theme) |> 
  mutate(n_tot_median = ceiling(median(n_tot[n_tot!=0]))) |> 
  ungroup() |> 
  mutate(
    recs_cat = factor(case_when(
      n_tot == 0 ~ "0",
      n_tot >= 4 ~ "4+",
      n_tot < 4 ~ "1-3"
    )),
    support_cat = factor(case_when(
      perc >= 80 ~ "80+",
      perc <80 ~ "<80"),
      levels = c("80+", "<80")),
    
    recs_median = factor(case_when(
      n_tot == 0 ~ "0",
      n_tot <= n_tot_median ~ paste0("1-",n_tot_median),
      n_tot > n_tot_median ~ paste0(n_tot_median+1,"+")
    )
    # ,levels = c("Fewer recommendations", 
    #            "More recommendations",
    #            "No recommendations")
    ),
    recs_median = fct_recode(recs_median, "1" = "1-1"),
    combined = factor(case_when(
      n_tot == 0 ~ "No recommendations",
      n_tot < n_tot_median & perc <80 ~ "Fewer recommendations, <80% support",
      n_tot < n_tot_median & perc >=80 ~ "Fewer recommendations, 80+% support",
      n_tot >= n_tot_median & perc <80 ~ "More recommendations, <80% support",
      n_tot >= n_tot_median & perc >=80 ~ "More recommendations, 80+% support"
    ),
    levels = c("More recommendations, 80+% support", "More recommendations, <80% support", 
               "Fewer recommendations, 80+% support", "Fewer recommendations, <80% support",
               "No recommendations")
    )
  ) |> 
  group_by(theme) |> 
  mutate(
    perc_c = perc-mean(perc, na.rm = TRUE),
    perc_c = case_when(is.na(perc_c) ~ 0, .default = perc_c)
  ) |> 
  ungroup() |> 
  left_join(theme_labels, join_by(theme == variable)) |> 
  rename(n_supported = n) |> 
  select(-c(response_upr))

n_sup_2_long_cycle <- sdg_data |> 
  filter(! cycle %in% c(
    "Cycle 4"
    # , "Cycle 3"
  )) |> 
  # filter(state_under_review %in% c(mmr_most$country_name)) |> 
  mutate(state_under_review = factor(state_under_review)) |> 
  # filter(response_upr %in% c("Supported", "Noted")) |> 
  group_by(state_under_review,iso3, response_upr, cycle, session, upr_session_number) |> 
  summarise(across(c(health_related:other_health_related), ~ sum(.x != "Other"))) |> 
  ungroup() |>
  filter(response_upr %in% c("Supported", "Noted")) |>
  pivot_longer(
    cols = health_related:other_health_related,
    names_to = "theme",
    values_to = "n"
  ) |> 
  arrange(state_under_review, cycle, theme, response_upr) |> 
  group_by(state_under_review, cycle, theme) |> 
  mutate(
    n_tot = sum(n),
    # perc = round(n/n_tot*100,1)
  ) |> 
  ungroup() |> 
  filter(response_upr == "Supported") |> 
  # group_by(cycle, theme) |> 
  # mutate(
  #   perc_c = perc-mean(perc, na.rm = TRUE),
  #   perc_c = case_when(is.na(perc_c) ~ 0, .default = perc_c)
  # ) |>
  # ungroup() |> 
  left_join(theme_labels, join_by(theme == variable)) |> 
  rename(n_supported = n) |> 
  select(-c(response_upr)) |> 
  left_join(read_csv(here("data", "upr_sessions.csv")), join_by(upr_session_number == session))

n_sup_2_cycle <- n_sup_2_long_cycle |> 
  select(-theme_label) |> 
  pivot_wider(names_from = theme, values_from = n_supported:n_tot, names_sep = "_cumulative_") |> 
  select(-state_under_review, -cycle, -session, -upr_session_number) |> 
  group_by(iso3) |> 
  mutate(
    across(tidyselect::contains("cumulative"), ~ cumsum(.x)),
  ) |> 
  ungroup() |> 
  mutate(year_1 = year+1, year_2 = year+2, year_3 = year+3, year_4 = year+4, 
         year_5 = year+5, year_6 = year+6, year_7 = year+7, year_8 = year+8, 
         year_9 = year+9, year_10 = year+10) |> 
  relocate(year_1:year_8, .after = year) |> 
  rename(year_0 = year)

n_sup_2 <- n_sup_2_long |>  
  select(-theme_label) |> 
  pivot_wider(names_from = theme, values_from = n_supported:perc_c)

cycle_years <- n_sup_2_long_cycle |> select(iso3, cycle, year) |> distinct() |> 
  bind_rows(
    tribble(
      ~iso3, ~cycle, ~year,
      "CAF", "Cycle 1", 2009,
      "ZAF", "Cycle 1", 2008
    )
  ) |> 
  arrange(iso3)
cycle_years_wide <- cycle_years |> 
  pivot_wider(names_from = cycle, values_from = year) |> 
  janitor::clean_names() |> 
  mutate(years2 = cycle_2 - cycle_1, 
         years3 = cycle_3 - cycle_2
  )

cycle_years <- sdg_data |> 
  filter(!cycle %in% c("Cycle 4")) |> 
  select(state_under_review, iso3, cycle, session, upr_session_number) |> 
  distinct() |> 
  left_join(read_csv(here("data", "upr_sessions.csv")), join_by(upr_session_number == session)) |> 
  bind_rows(
    tribble(
      ~state_under_review, ~iso3, ~cycle, ~session, ~upr_session_number, ~year,
      "Central African Republic", "CAF", "Cycle 1", "12th session", 12, 2009,
    )
  ) |> 
  arrange(iso3, cycle) |> 
  filter(!is.na(iso3))

cycle_years_wide <- cycle_years |> 
  select(-session, -upr_session_number) |> 
  pivot_wider(names_from = cycle, values_from = year, names_prefix = "year") |> 
  janitor::clean_names()

# Create the table data masterfile ----
dat_table <- MMR |> 
  filter(!is.na(country_name)) |> 
  filter(country_name!="Cook Islands", country_name != "Greenland") |> 
  select(ParentLocation, COUNTRY, country_name, YEAR, NumericValue) |> 
  mutate(NumericValue = round(NumericValue)) |> 
  rename(MMR = NumericValue) |> 
  right_join(state_geo |> filter(status == "member"), join_by(COUNTRY == iso3)) |> 
  mutate(
    mmr_cat4 = factor(case_when(
      MMR < 20 ~ "<20",
      MMR < 100 ~ "20-99",
      MMR < 300 ~ "100-299",
      MMR >= 300 ~ "300+",
      .default = NA), 
      levels = c("<20", "20-99","100-299", "300+")
    ),
    
    mmr_cat5 = factor(case_when(
      MMR < 70 ~ "<70",
      MMR < 120 ~ "70-119",
      MMR < 220 ~ "120-219",
      MMR < 300 ~ "220-299",
      MMR >= 300 ~ "300+",
      .default = NA), 
      levels = c("<70", "70-119", "120-219", "220-299", "300+")
    ),
    
    mmr_cat3 = factor(case_when(
      MMR < 20 ~ "<20",
      MMR < 100 ~ "20-99",
      MMR >= 100 ~ "100+",
      .default = NA), 
      levels = c("<20", "20-99","100+")
    ),
    
    mmr_cat2 = factor(case_when(
      MMR < 100 ~ "<100",
      MMR >= 100 ~ "100+",
      .default = NA), 
      levels = c("<100","100+")
    )
  ) |> 
  # filter(YEAR >= 1995) |> 
  # filter(YEAR %in% c(1995,2005, 2007, 2008, 2023)) |>
  left_join(mmr_data_WHO |> select(country_iso_3_code, year, livebirths), join_by(COUNTRY == country_iso_3_code, YEAR == year)) |> 
  left_join(HDI, join_by(COUNTRY == iso3, YEAR == year)) |> 
  left_join(GHED_CHEGDP_SHA2011 |> select(COUNTRY, YEAR, NumericValue) |> rename(CHEGDP = NumericValue),
            join_by(COUNTRY == COUNTRY, YEAR == YEAR)) |> 
  arrange(COUNTRY, YEAR) |> 
  pivot_wider(values_from = c(MMR, mmr_cat4,mmr_cat5, mmr_cat3, mmr_cat2, livebirths, HDI, CHEGDP), names_from = YEAR) |> 
  mutate(
    MMR_2000_C = datawizard::standardize(MMR_2000, scale = FALSE),
    MMR_2000_full = MMR_2000,
    MMR_2005_C = datawizard::standardize(MMR_2005, scale = FALSE),
    MMR_2005_full = MMR_2005,
    MMR_2008_C = datawizard::standardize(MMR_2008, scale = FALSE),
    MMR_2008_full = MMR_2008,
    MMR_2007_C = datawizard::standardize(MMR_2007, scale = FALSE),
    MMR_2007_full = MMR_2007,
    MMR_2004_C = datawizard::standardize(MMR_2004, scale = FALSE),
    MMR_2004_full = MMR_2004) |> 
  left_join(NMIRF |> select(iso3, nmirf_classification), join_by(COUNTRY == iso3)) |> 
  mutate(nmirf_classification = fct_na_value_to_level(nmirf_classification, level = "Unknown")) |> 
  left_join(GDP_table |> select(-country_name), join_by(COUNTRY==country_code)) |> 
  left_join(WB_income_group |> select(-country), join_by(COUNTRY == iso3)) |> 
  left_join(literacy_table |> select(country_code, literacy_long), join_by(COUNTRY == country_code)) |> 
  left_join(institutional_birth_table) |> 
  left_join(skilled_birth_table) |> 
  left_join(skilled_birth_change) |> 
  left_join(anc4_table) |> 
  left_join(family_planning_table) |> 
  # left_join(abortion_deaths_table, join_by(country_name == country)) |> 
  left_join(world_abortion_laws |> select(country, category), join_by(country_name==country)) |> 
  left_join(unintended_pregnancy_table) |> 
  left_join(UHC_SCI_RMNCH_table, join_by(COUNTRY == SpatialDim)) |> 
  # left_join(governance_table |> select(iso3, government_effectiveness_baseline), join_by(COUNTRY == iso3)) |> 
  left_join(WGI_governance |> select(-year), join_by(COUNTRY == iso3)) |> 
  left_join(WGI_political_stability |> select(-year), join_by(COUNTRY == iso3)) |> 
  
  left_join(vdem_data |> filter(year >= 2007) |> 
              filter(!is.na(v2xcs_ccsi)) |> 
              group_by(country_name) |> 
              slice_min(year, n=1) |> 
              ungroup() |> 
              rename(
                v2xcs_ccsi_baseline = v2xcs_ccsi,
                e_v2xcs_ccsi_3C_cat_baseline = e_v2xcs_ccsi_3C_cat,
                v2x_cspart_baseline = v2x_cspart,
                e_v2x_cspart_3C_cat_baseline = e_v2x_cspart_3C_cat) |> 
              select(-c(country_name, year, e_v2xcs_ccsi_3C, e_v2x_cspart_3C)),
            join_by(COUNTRY == iso3)) |> 
  rename(abortion_law = category) |> 
  # mutate(abortion_law = case_when(
  #   abortion_law == "Varies at State level" ~ NA,
  #   .default = abortion_law
  # )) |>
  left_join(UNFPA_CPR_any_table, join_by(COUNTRY == iso3)) |> 
  rename(contraceptive_any = CPR_any) |> 
  rename(contraceptive_any_cat = CPR_any_cat) |> 
  left_join(CPR_any, join_by(COUNTRY == iso3)) |> 
  # left_join(state_geo, join_by(COUNTRY == iso3)) |> 
  # # left_join(n_sup_mh, join_by(country_name == state_under_review)) |> 
  # filter(status == "member") |> 
  mutate(
    FCS_status = fct_na_value_to_level(FCS_status, level = "Other"),
    FCS_status = fct_relevel(FCS_status, "Other"),
    conflict_status = factor(case_when(
      FCS_status == "Conflict" ~ "Conflict",
      .default = "Other"
    ), levels = c("Other", "Conflict")),
    FCS_cat = factor(case_when(
      FCS_status %in% c("Conflict", "Institutional and social fragility") ~ "FCS",
      .default = "Not FCS"
    ), levels = c("Not FCS", "FCS")),
    
    FCS_status_2006 = fct_na_value_to_level(FCS_status_2006, level = "Not FCS"),
    FCS_status_2006 = fct_relevel(FCS_status_2006, "Not FCS"),
    
    FCS_status_2007 = fct_na_value_to_level(FCS_status_2007, level = "Not FCS"),
    FCS_status_2007 = fct_relevel(FCS_status_2007, "Not FCS"),
    
    FCS_status_2008 = fct_na_value_to_level(FCS_status_2008, level = "Not FCS"),
    FCS_status_2008 = fct_relevel(FCS_status_2008, "Not FCS"),
    
    FCS_count = case_when(is.na(FCS_count) ~ 0, .default = FCS_count),
    
    FCS_count_cat = factor(case_when(
      FCS_count == 0 ~ "0",
      FCS_count <= 8 ~ "1-8",
      FCS_count <= 15 ~ "9-15",
      FCS_count > 15 ~ "16+"
    ), levels = c("0", "1-8", "9-15", "16+")),
    
    FCS_count_name = fct_na_value_to_level(FCS_count_name, level = "FCS status < 10 years"),
    FCS_count_name = fct_relevel(FCS_count_name, "FCS status < 10 years"),
    
    FCS_2023 = fct_na_value_to_level(FCS_2023, level = "Other"),
    FCS_2023 = fct_relevel(FCS_2023, "Other"),
    FCS_2023_cat = factor(case_when(
      FCS_2023 %in% c("Conflict", "Institutional and social fragility") ~ "FCS",
      .default = "Not FCS"
    ), levels = c("Not FCS", "FCS"))
  ) |> 
  left_join(n_sup_2, join_by(country_name == state_under_review)) |> 
  mutate(
    MMR_change = MMR_2023 - MMR_2005,
    MMR_perc_change = (MMR_2023-MMR_2005)/MMR_2005*100,
    MMR_ratio = MMR_2023/MMR_2005,
    MMR_ratio_log = log(MMR_ratio),
    MMR_log_change = log(MMR_2023)-log(MMR_2005),
    
    # Historical change
    MMR_historical_change = MMR_2005 - MMR_1995,
    MMR_historical_log_change = log(MMR_2005)-log(MMR_1995),
    
    MMR_log_change_cat2 = factor(case_when(
      MMR_log_change >= 0 ~ "No change or Increase",
      MMR_log_change < 0 ~ "Decrease"
    )),
    MMR_change_cat = factor(case_when(
      MMR_change >= 0 ~ "Same/Increase",
      MMR_change < -200 ~ "Major decrease",
      MMR_change < -50 ~ "Moderate decrease",
      MMR_change < 0 ~ "Minor decrease"
    ), 
    levels = c("Same/Increase", "Minor decrease", "Moderate decrease", "Major decrease")
    )
  ) |> 
  relocate(MMR_change, MMR_change_cat, MMR_perc_change, MMR_log_change, MMR_historical_change, MMR_historical_log_change, MMR_ratio, MMR_ratio_log, .after = MMR_2023) |> 
  mutate(GDP_05_19_log = log(GDP_2019) - log(GDP_2005)) |> 
  relocate(GDP_05_19_log, .after = GDP_05_19) |> 
  mutate(
    GDP_2005_cat = factor(case_when(
      GDP_2005<2000 ~ "<2,000",
      GDP_2005<5000 ~ "<5,000",
      GDP_2005<10000 ~ "<10,000",
      GDP_2005>=10000 ~ "10,000+"
    ), levels = c("<2,000", "<5,000", "<10,000",
                  "10,000+"))
  ) |> 
  droplevels()

excluded_dat_table <- dat_table |> filter(MMR_2005 < 70)
dat_table <- dat_table |> filter(MMR_2005 >= 70)


dat_table_long <- dat_table |> 
  pivot_longer(names_to = "year", values_to = "MMR_long", cols = MMR_1985:MMR_2023) |> 
  relocate(MMR_long, year, .after = country_name) |> 
  mutate(year = as.integer(str_remove(year, "MMR_"))) |> 
  filter(year >= 2000) |>
  left_join(cycle_years_wide |> select(-state_under_review), join_by(COUNTRY == iso3)) |> 
  left_join(mmr_data_WHO |> select(-c(mmr_WHO, mmr_calc)),
            join_by(year == year, COUNTRY == country_iso_3_code)
  ) |> 
  left_join(skilled_birth |> 
              select(COUNTRY, YEAR, NumericValue, value_cat) |> 
              rename(skilled_birth_long = NumericValue, 
                     skilled_birth_long_cat = value_cat),
            join_by(COUNTRY == COUNTRY, year == YEAR)) |> 
  left_join(UNFPA_CPR_any_long,
            join_by(COUNTRY == iso3, year == year)) |> 
  
  left_join(literacy_female_long |> select(country_code, year, literacy_female),
            join_by(COUNTRY == country_code, year == year)) |> 
  left_join(GDP_long |> select(country_code, year, GDP_long),
            join_by(COUNTRY == country_code, year == year)) |> 
  left_join(HDI |> rename(HDI_long = HDI), join_by(COUNTRY == iso3, year == year)) |> 
  left_join(GHED_CHEGDP_SHA2011 |> select(COUNTRY, YEAR, NumericValue) |> rename(CHEGDP_long = NumericValue),
            join_by(COUNTRY == COUNTRY, year == YEAR)) |> 
  left_join(WGI |> select(-country),
            join_by(COUNTRY == iso3, year == year)) |> 
  left_join(vdem_data |> select(-country_name), join_by(COUNTRY == iso3, year == year)) |> 
  left_join(FCS_all |> select(-FCS_status2) |> rename(FCS_long = FCS_status), 
            join_by(COUNTRY ==iso3, year==year)) |> 
  mutate(
    FCS_long = case_when(FCS_long == "FCS" ~ 1, .default = 0),
    GDP_long_c = datawizard::standardize(GDP_long),
    HDI_long_c = datawizard::standardize(HDI_long),
    CHEGDP_long_c = datawizard::standardize(CHEGDP_long),
    literacy_female_c = datawizard::standardize(literacy_female),
    n_tot_Maternal_health_C = datawizard::standardize(n_tot_Maternal_health, scale = FALSE)
  ) |> 
  mutate(
    MMR_long_log = log(MMR_long),
    skilled_birth_long_log = log(skilled_birth_long),
    skilled_birth_long_p = skilled_birth_long/100,
    skilled_birth_long_p_squeezed = case_when(
      skilled_birth_long_p >= 1 ~ 0.99,
      skilled_birth_long_p <= 0 ~ 0.01,
      .default = skilled_birth_long_p
    ),
    skilled_birth_long_p_squeezed2 = (skilled_birth_long_p * (n() - 1) + 0.5) / n(),
    skilled_birth_long_logit = log(skilled_birth_long_p_squeezed/(1-skilled_birth_long_p_squeezed)),
    skilled_birth_long_logit2 = log(skilled_birth_long_p_squeezed2/(1-skilled_birth_long_p_squeezed2)),
    CPR_any_long_log = log(CPR_any_long),
    CPR_any_long_p = CPR_any_long/100,
    CPR_any_long_logit = log(CPR_any_long_p/(1-CPR_any_long_p))
  ) |> 
  relocate(
    MMR_long_log, 
    skilled_birth_long, skilled_birth_long_log, skilled_birth_long_p, 
    skilled_birth_long_p_squeezed, skilled_birth_long_p_squeezed2, 
    skilled_birth_long_logit,skilled_birth_long_logit2,
    CPR_any_long, CPR_any_long_log, CPR_any_long_p, CPR_any_long_logit,
    literacy_female,literacy_female_c, 
    GDP_long,GDP_long_c, 
    .after = MMR_long
  ) |> 
  mutate(YEAR = year) |> 
  mutate(year = year - 2005) |> # zero-center the year variable (2005 = 0)
  mutate(
    year_upr = YEAR - year_cycle_1, # zero-center the year to the year of the country's first UPR cycle
    year_post = pmax(0, year_upr), # set all pre-upr years to 0
    year_upr2 = case_when(YEAR >= year_cycle_1 ~ 1, .default = 0)
  ) |> 
  mutate(
    spline_years_3 = factor(case_when(
      YEAR < 2008 ~ "1: 2000-2007",
      YEAR <=2015 ~ "2: 2008-2015",
      YEAR >2015 ~ "3: 2016-2023"
    )),
    spline_years_2 = factor(case_when(
      YEAR < 2008 ~ "1: 2000-2007",
      YEAR >=2008 ~ "2: 2008-2023"
    ))
  ) |> 
  group_by(country_name) |> 
  arrange(year, .by_group = TRUE) |> 
  group_by(country_name) |> 
  mutate(
    FCS_cumulative = cumsum(FCS_long)
  ) |> 
  ungroup() |> 
  relocate(YEAR, .after = year) |> 
  group_by(country_name) |> 
  mutate(
    MMR_full = sum(!is.na(MMR_long_log)),
    SBA_full = sum(!is.na(skilled_birth_long_p_squeezed)),
    CPR_full = sum(!is.na(CPR_any_long_p)),
    GDP_full = sum(!is.na(GDP_long)),
    HDI_full = sum(!is.na(HDI_long_c))
  ) |> 
  ungroup() |> 
  filter(GDP_full > 0) |>
  mutate(FCS_cumulative_c = datawizard::standardize(FCS_cumulative, scale = FALSE)) |> 
  droplevels() |> 
  mutate(    
    v2xcs_ccsi_baseline_C = datawizard::standardize(v2xcs_ccsi_baseline, scale = FALSE),
    v2x_cspart_baseline_C = datawizard::standardise(v2x_cspart_baseline, scale = FALSE),
    government_effectiveness_baseline_C = datawizard::standardise(government_effectiveness_baseline, scale = FALSE),
    government_effectiveness_C = datawizard::standardise(government_effectiveness, scale = FALSE)
  )
# left_join(n_sup_2_cycle, join_by(COUNTRY == iso3, YEAR == year_5)) |> 
# arrange(COUNTRY, YEAR) |> 
# group_by(COUNTRY) |> 
# mutate(
#   across(tidyselect::starts_with(c("n_tot_cumulative","n_supported_cumulative")), ~ case_when(YEAR == 2005 ~ 0, .default = .x))
#   ) |> 
# fill(
#   starts_with(c("n_supported_cumulative_", "n_tot_cumulative_")),
#   .direction = "down"
# ) |> 
# ungroup()

# dat_table_long |> filter(GDP_full < 5) |> select(country_name, GDP_full) |> distinct()

# get the list of countries included in the analyis
analysis_countries <- dat_table_long |> select(COUNTRY) |> distinct() |> pull(COUNTRY)
# Update the dataset of the excluded countries
excluded_dat_table <- bind_rows(excluded_dat_table, dat_table |> 
                                  filter(!COUNTRY %in% c(analysis_countries)))
# Update the wide datatable to include only the analysis countries
dat_table <- dat_table |> 
  filter(COUNTRY %in% c(analysis_countries))

# Save date-stamped datasets in case an older dataset is needed
saveRDS(dat_table, file = here("output", paste0("dat_table_", Sys.Date(),".rds")))
saveRDS(dat_table_long, file = here("output", paste0("dat_table_long_", Sys.Date(),".rds")))